### ISSUE TITLE
Add Threatstream to apikey.yaml

### ISSUE THREAD

**Issue by AHewitt** [diogo-fern/malsub#15]
Threatstream is missing from the apikey.yaml file, we simply need to add it:

```
ThreatStream:
    apikey:
        api_key: <apikey>
    user:
        username: <apiuser>
```
